import "./globals.css";
import { Poppins } from '@next/font/google'

export const metadata = {
  title: "Job Board",
  description: "Generated by create next app",
};
const poppins = Poppins({subsets:['latin'], weight:['500']})
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
